apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-gateway
  namespace: a2a-mcp
  labels:
    app: event-gateway
    component: gateway
    layer: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: event-gateway
        component: gateway
        layer: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: event-gateway
        image: a2a-mcp/event-gateway:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "8000"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        - name: RATE_LIMIT_CAPACITY
          value: "60"
        - name: RATE_LIMIT_REFILL_RATE
          value: "1.0"
        - name: MAX_RETRIES
          value: "3"
        - name: RETRY_MIN_WAIT
          value: "1.0"
        - name: RETRY_MAX_WAIT
          value: "10.0"
        - name: SUB_AGENT_ROUTES
          valueFrom:
            configMapKeyRef:
              name: event-gateway-config
              key: sub_agent_routes.json
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: config-volume
        configMap:
          name: event-gateway-config
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: event-gateway
  namespace: a2a-mcp
  labels:
    app: event-gateway
    component: gateway
    layer: gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: event-gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-gateway-config
  namespace: a2a-mcp
data:
  sub_agent_routes.json: |
    {
      "cpu_high_usage": "http://sub-agent-cpu:8080/events",
      "memory_high_usage": "http://sub-agent-memory:8080/events",
      "disk_space_low": "http://sub-agent-disk:8080/events",
      "network_issue": "http://sub-agent-network:8080/events",
      "default": "http://sub-agent-general:8080/events"
    }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: event-gateway-hpa
  namespace: a2a-mcp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-gateway
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-gateway-ingress
  namespace: a2a-mcp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - event-gateway.a2a-mcp.example.com
    secretName: event-gateway-tls
  rules:
  - host: event-gateway.a2a-mcp.example.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: event-gateway
            port:
              name: http 